services:
    _defaults:
        autowire: true
        autoconfigure: true

    Postyou\ContaoPageTeaserBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection}
